# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            artoo.js
tagline:          'The client-side scraping companion.'
description:      'The client-side scraping companion.'
baseurl:          '/artoo'

author:
  name:           'Yomguithereal'
  url:            https://github.com/Yomguithereal

# Custom vars
version:          0.4.2

sidebar:
  - url: 'quick_start'
    title: 'Quick Start'
  - url: 'hacker_news'
    title: 'Hacker News scraper'
  - sep
  - url: 'methods'
    title: 'Methods'
  - url: 'settings'
    title: 'Settings'
  - url: 'jquery'
    title: 'jQuery injection'
  - url: 'node'
    title: 'Node.js'
  - url: 'gulp'
    title: 'Gulp plugin'
  - url: 'generator'
    title: 'Bookmarklet generator'
  - sep
  - url: 'changelog'
    title: 'Changelog'

github:
  repo:           https://github.com/medialab/artoo

medialab:
  url:            'http://www.medialab.sciences-po.fr/'

bookmarklets:
  artoo:          'javascript: (function(){var t={},e=!0;if("object"==typeof this.artoo&&(artoo.settings.reload||(artoo.log.verbose("artoo already exists within this page. No need to inject him again."),artoo.loadSettings(t),artoo.exec(),e=!1)),e){var o=document.getElementsByTagName("body")[0];o||(o=document.createElement("body"),document.documentElement.appendChild(o));var a=document.createElement("script");console.log("artoo.js is loading..."),a.src="//medialab.github.io/artoo/public/dist/artoo-latest.min.js",a.type="text/javascript",a.id="artoo_injected_script",a.setAttribute("settings",JSON.stringify(t)),o.appendChild(a)}}).call(this);'
  beeping:        'javascript: (function(){var t={log:{beeping:!0}},e=!0;if("object"==typeof this.artoo&&(artoo.settings.reload||(artoo.log.verbose("artoo already exists within this page. No need to inject him again."),artoo.loadSettings(t),artoo.exec(),e=!1)),e){var o=document.getElementsByTagName("body")[0];o||(o=document.createElement("body"),document.documentElement.appendChild(o));var a=document.createElement("script");console.log("artoo.js is loading..."),a.src="//medialab.github.io/artoo/public/dist/artoo-latest.min.js",a.type="text/javascript",a.id="artoo_injected_script",a.setAttribute("settings",JSON.stringify(t)),o.appendChild(a)}}).call(this);'
  hackernews:     >
    javascript: (function(){var t={eval:&#39;"(function(t){function e(t){return t.find(\\"td.title:last > a\\").attr(\\"href\\")}var r={iterator:\\"tr tr:has(td.title:has(a)):not(:last)\\",data:{title:{sel:\\".title a\\"},url:{sel:\\".title a\\",attr:\\"href\\"},domain:{sel:\\".comhead\\",method:function(t){return t(this).text().trim().replace(/[\\\\(\\\\)]/g,\\"\\")}},score:function(t){return+t(this).find(\\"+ tr [id^=score]\\").text().replace(\\" points\\",\\"\\")},user:{sel:\\"+ tr a[href^=user]\\",method:function(t){return t(this).length?t(this).text():null}},nb_comments:{sel:\\"+ tr a[href^=item]\\",method:function(t){var e=+t(this).text().replace(\\" comments\\",\\"\\");return isNaN(e)?0:e}}}};artoo.log.debug(\\"Starting the scraper...\\");var a=artoo.scrape(r);artoo.ajaxSpider(function(r,a){return e(r?a:t(document))},{limit:2,scrape:r,concat:!0,done:function(t){artoo.log.debug(\\"Finished retrieving data. Downloading...\\"),artoo.savePrettyJson(a.concat(t),{filename:\\"hacker_news.json\\"})}})}).call(this,artoo.$);"&#39;},e=!0;if("object"==typeof this.artoo)artoo.settings.reload||(artoo.log.verbose("artoo already exists within this page. No need to inject him again."),artoo.loadSettings(t),artoo.exec(),e=!1);else if(e){var r=document.getElementsByTagName("body")[0],o=document.createElement("script");console.log("artoo is loading..."),o.src="//medialab.github.io/artoo/public/dist/artoo-latest.min.js",o.type="text/javascript",o.id="artoo_injected_script",o.setAttribute("settings",JSON.stringify(t)),r.appendChild(o)}}).call(this);
